version: '3.9'

services:
  tile38-1:
    build:
      context: ./tile-38-master
      dockerfile: Dockerfile
    container_name: "tile38-1"
    network_mode: "host"
    command: [ "tile38-server", "-d", "/data", "--appendonly", "yes","-vv", "-p", "9851"]
    
  tile38-2:
    build:
      context: ./tile-38-slave
      dockerfile: Dockerfile
    container_name: "tile38-2"
    network_mode: "host"
    command: [ "tile38-server", "-d", "/data", "--appendonly", "yes","-vv", "-p", "9852"]

  tile38-3:
    build:
      context: ./tile-38-slave
      dockerfile: Dockerfile
    container_name: "tile38-3"
    network_mode: "host"
    command: [ "tile38-server", "-d", "/data", "--appendonly", "yes","-vv", "-p", "9853"]

  redis-sentinel1:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    container_name: "redis-sentinel1"
    network_mode: "host"
    environment:
      - SENTINEL_PORT=5000
    
  redis-sentinel2:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    container_name: "redis-sentinel2"
    network_mode: "host"
    environment:
      - SENTINEL_PORT=5001
   

  redis-sentinel3:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    container_name: "redis-sentinel3"
    network_mode: "host"
    environment:
      - SENTINEL_PORT=5002
   

